name: Check code quality

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_VERSION: 22.15.0
  PNPM_VERSION: 10.10.0

concurrency:
  group: qualityCheck-${{ github.ref }}
  cancel-in-progress: true

jobs:
  qualityCheck:
    name: Check code quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Setup project'
        uses: ./.github/actions/setup-project

      - name: 'Lint'
        run: pnpm lint

      - name: 'Test'
        run: pnpm test

      - name: 'Build project'
        run: pnpm build
